version: '2'
services:
  limesurvey:
    ports:
      - "80:80"
      - "587:587"
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - upload:/app/upload
    image:
      vlanderson/limesurvey:latest
